apiVersion: v1
kind: Service
metadata:
  name: fussball-service
  labels:
    app: fussball-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 8081
    nodePort: 30080
  selector:
    app: fussball-service
