apiVersion: apps/v1
kind: Deployment
metadata:
  name: fussball-service
  labels:
    app: fussball-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fussball-service
  template:
    metadata:
      labels:
        app: fussball-service
    spec:
      containers:
      - name: fussball
        image: eu.gcr.io/pa-dnoguerol/fussball:0.0.1
        ports:
        - containerPort: 8080